name: shorthaulenv
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - ampl-asl=1.0.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cyipopt=1.6.1
  - expat=2.7.1
  - icc_rt=2022.1.0
  - intel-openmp=2025.0.0
  - ipopt=3.14.19
  - libblas=3.9.0
  - libffi=3.4.4
  - libflang=5.0.0
  - liblapack=3.9.0
  - libmpdec=4.0.0
  - libpgmath=2021.08.06
  - libzlib=1.3.1
  - llvm-meta=5.0.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mdolab-baseclasses=1.8.4
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - msys2-conda-epoch=20160418
  - mumps-seq=5.7.3
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openmp=5.0.0
  - openssl=3.5.4
  - packaging=25.0
  - pip=25.2
  - pyoptsparse=2.14.3
  - python=3.13.9
  - python_abi=3.13
  - scipy=1.16.0
  - setuptools=72.1.0
  - sqlite=3.50.2
  - sqlitedict=2.1.0
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aviary==0.10.0.dev0
      - bleach==6.2.0
      - bokeh==3.8.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - colorcet==3.1.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dymos==1.15.0
      - fonttools==4.60.1
      - holoviews==1.21.0
      - hvplot==0.12.1
      - idna==3.11
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - linkify-it-py==2.0.3
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - narwhals==2.9.0
      - networkx==3.5
      - openmdao==3.41.0
      - pandas==2.3.3
      - panel==1.8.2
      - param==2.2.1
      - parameterized==0.9.0
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.3
      - requests==2.32.5
      - six==1.17.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - webencodings==0.5.1
      - xyzservices==2025.4.0
