import numpy as np
phase_info = {   'pre_mission': {'include_takeoff': False, 'optimize_mass': True},
    'climb_1': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                   'user_options': {   'num_segments': 3,
                                       'order': 3,
                                       'mach_optimize': False,
                                       'mach_polynomial_order': 1,
                                       'mach_initial': (   np.float64(0.3),
                                                           'unitless'),
                                       'mach_final': (   np.float64(0.72),
                                                         'unitless'),
                                       'mach_bounds': (   (   np.float64(0.27999999999999997),
                                                              np.float64(0.74)),
                                                          'unitless'),
                                       'altitude_optimize': False,
                                       'altitude_polynomial_order': 1,
                                       'altitude_initial': (   np.float64(0.0),
                                                               'ft'),
                                       'altitude_final': (   np.float64(40000.0),
                                                             'ft'),
                                       'altitude_bounds': (   (   0.0,
                                                                  np.float64(40500.0)),
                                                              'ft'),
                                       'throttle_enforcement': 'path_constraint',
                                       'time_initial_bounds': (   (0.0, 0.0),
                                                                  'min'),
                                       'time_duration_bounds': (   (   np.float64(10.0),
                                                                       np.float64(30.0)),
                                                                   'min'),
                                       'distance_solve_segments': False},
                   'initial_guesses': {   'time': (   [   np.float64(0.0),
                                                          np.float64(20.0)],
                                                      'min')}},
    'cruise_1': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                    'user_options': {   'num_segments': 3,
                                        'order': 3,
                                        'mach_optimize': False,
                                        'mach_polynomial_order': 1,
                                        'mach_initial': (   np.float64(0.72),
                                                            'unitless'),
                                        'mach_final': (   np.float64(0.72),
                                                          'unitless'),
                                        'mach_bounds': (   (   np.float64(0.7),
                                                               np.float64(0.74)),
                                                           'unitless'),
                                        'altitude_optimize': False,
                                        'altitude_polynomial_order': 1,
                                        'altitude_initial': (   np.float64(40000.0),
                                                                'ft'),
                                        'altitude_final': (   np.float64(40000.0),
                                                              'ft'),
                                        'altitude_bounds': (   (   np.float64(39500.0),
                                                                   np.float64(40500.0)),
                                                               'ft'),
                                        'throttle_enforcement': 'boundary_constraint',
                                        'time_initial_bounds': (   (   np.float64(10.0),
                                                                       np.float64(30.0)),
                                                                   'min'),
                                        'time_duration_bounds': (   (   np.float64(25.0),
                                                                        np.float64(75.0)),
                                                                    'min'),
                                        'distance_solve_segments': False},
                    'initial_guesses': {   'time': (   [   np.float64(20.0),
                                                           np.float64(50.0)],
                                                       'min')}},
    'descent_1': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                     'user_options': {   'num_segments': 3,
                                         'order': 3,
                                         'mach_optimize': False,
                                         'mach_polynomial_order': 1,
                                         'mach_initial': (   np.float64(0.72),
                                                             'unitless'),
                                         'mach_final': (   np.float64(0.5),
                                                           'unitless'),
                                         'mach_bounds': (   (   np.float64(0.48),
                                                                np.float64(0.74)),
                                                            'unitless'),
                                         'altitude_optimize': False,
                                         'altitude_polynomial_order': 1,
                                         'altitude_initial': (   np.float64(40000.0),
                                                                 'ft'),
                                         'altitude_final': (   np.float64(0.0),
                                                               'ft'),
                                         'altitude_bounds': (   (   0.0,
                                                                    np.float64(40500.0)),
                                                                'ft'),
                                         'throttle_enforcement': 'path_constraint',
                                         'time_initial_bounds': (   (   np.float64(35.0),
                                                                        np.float64(105.0)),
                                                                    'min'),
                                         'time_duration_bounds': (   (   np.float64(10.0),
                                                                         np.float64(30.0)),
                                                                     'min'),
                                         'distance_solve_segments': False},
                     'initial_guesses': {   'time': (   [   np.float64(70.0),
                                                            np.float64(20.0)],
                                                        'min')}},
    'post_mission': {   'include_landing': False,
                        'constrain_range': True,
                        'target_range': (np.float64(648.96), 'nmi')}}
