phase_info = {   'pre_mission': {'include_takeoff': False, 'optimize_mass': True},
    'climb_1': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                   'user_options': {   'num_segments': 5,
                                       'order': 3,
                                       'mach_optimize': False,
                                       'mach_polynomial_order': 1,
                                       'mach_initial': (   np.float64(0.3),
                                                           'unitless'),
                                       'mach_final': (   np.float64(0.5),
                                                         'unitless'),
                                       'mach_bounds': (   (   np.float64(0.27999999999999997),
                                                              np.float64(0.52)),
                                                          'unitless'),
                                       'altitude_optimize': False,
                                       'altitude_polynomial_order': 1,
                                       'altitude_initial': (   np.float64(0.0),
                                                               'ft'),
                                       'altitude_final': (   np.float64(39202.0),
                                                             'ft'),
                                       'altitude_bounds': (   (   0.0,
                                                                  np.float64(39702.0)),
                                                              'ft'),
                                       'throttle_enforcement': 'path_constraint',
                                       'time_initial_bounds': (   (0.0, 0.0),
                                                                  'min'),
                                       'time_duration_bounds': (   (   np.float64(26.5),
                                                                       np.float64(79.5)),
                                                                   'min'),
                                       'distance_solve_segments': False},
                   'initial_guesses': {   'time': (   [   np.float64(0.0),
                                                          np.float64(53.0)],
                                                      'min')}},
    'climb_2': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                   'user_options': {   'num_segments': 5,
                                       'order': 3,
                                       'mach_optimize': False,
                                       'mach_polynomial_order': 1,
                                       'mach_initial': (   np.float64(0.5),
                                                           'unitless'),
                                       'mach_final': (   np.float64(0.5),
                                                         'unitless'),
                                       'mach_bounds': (   (   np.float64(0.48),
                                                              np.float64(0.52)),
                                                          'unitless'),
                                       'altitude_optimize': False,
                                       'altitude_polynomial_order': 1,
                                       'altitude_initial': (   np.float64(39202.0),
                                                               'ft'),
                                       'altitude_final': (   np.float64(45533.0),
                                                             'ft'),
                                       'altitude_bounds': (   (   np.float64(38702.0),
                                                                  np.float64(46033.0)),
                                                              'ft'),
                                       'throttle_enforcement': 'boundary_constraint',
                                       'time_initial_bounds': (   (   np.float64(26.5),
                                                                      np.float64(79.5)),
                                                                  'min'),
                                       'time_duration_bounds': (   (   np.float64(89.0),
                                                                       np.float64(267.0)),
                                                                   'min'),
                                       'distance_solve_segments': False},
                   'initial_guesses': {   'time': (   [   np.float64(53.0),
                                                          np.float64(178.0)],
                                                      'min')}},
    'descent_1': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                     'user_options': {   'num_segments': 5,
                                         'order': 3,
                                         'mach_optimize': False,
                                         'mach_polynomial_order': 1,
                                         'mach_initial': (   np.float64(0.5),
                                                             'unitless'),
                                         'mach_final': (   np.float64(0.5),
                                                           'unitless'),
                                         'mach_bounds': (   (   np.float64(0.48),
                                                                np.float64(0.52)),
                                                            'unitless'),
                                         'altitude_optimize': False,
                                         'altitude_polynomial_order': 1,
                                         'altitude_initial': (   np.float64(45533.0),
                                                                 'ft'),
                                         'altitude_final': (   np.float64(39597.0),
                                                               'ft'),
                                         'altitude_bounds': (   (   np.float64(39097.0),
                                                                    np.float64(46033.0)),
                                                                'ft'),
                                         'throttle_enforcement': 'boundary_constraint',
                                         'time_initial_bounds': (   (   np.float64(115.5),
                                                                        np.float64(346.5)),
                                                                    'min'),
                                         'time_duration_bounds': (   (   np.float64(29.0),
                                                                         np.float64(87.0)),
                                                                     'min'),
                                         'distance_solve_segments': False},
                     'initial_guesses': {   'time': (   [   np.float64(231.0),
                                                            np.float64(58.0)],
                                                        'min')}},
    'descent_2': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                     'user_options': {   'num_segments': 5,
                                         'order': 3,
                                         'mach_optimize': False,
                                         'mach_polynomial_order': 1,
                                         'mach_initial': (   np.float64(0.5),
                                                             'unitless'),
                                         'mach_final': (   np.float64(0.5),
                                                           'unitless'),
                                         'mach_bounds': (   (   np.float64(0.48),
                                                                np.float64(0.52)),
                                                            'unitless'),
                                         'altitude_optimize': False,
                                         'altitude_polynomial_order': 1,
                                         'altitude_initial': (   np.float64(39597.0),
                                                                 'ft'),
                                         'altitude_final': (   np.float64(26540.0),
                                                               'ft'),
                                         'altitude_bounds': (   (   np.float64(26040.0),
                                                                    np.float64(40097.0)),
                                                                'ft'),
                                         'throttle_enforcement': 'boundary_constraint',
                                         'time_initial_bounds': (   (   np.float64(144.5),
                                                                        np.float64(433.5)),
                                                                    'min'),
                                         'time_duration_bounds': (   (   np.float64(32.5),
                                                                         np.float64(97.5)),
                                                                     'min'),
                                         'distance_solve_segments': False},
                     'initial_guesses': {   'time': (   [   np.float64(289.0),
                                                            np.float64(65.0)],
                                                        'min')}},
    'descent_3': {   'subsystem_options': {   'core_aerodynamics': {   'method': 'computed'}},
                     'user_options': {   'num_segments': 5,
                                         'order': 3,
                                         'mach_optimize': False,
                                         'mach_polynomial_order': 1,
                                         'mach_initial': (   np.float64(0.5),
                                                             'unitless'),
                                         'mach_final': (   np.float64(0.5),
                                                           'unitless'),
                                         'mach_bounds': (   (   np.float64(0.48),
                                                                np.float64(0.52)),
                                                            'unitless'),
                                         'altitude_optimize': False,
                                         'altitude_polynomial_order': 1,
                                         'altitude_initial': (   np.float64(26540.0),
                                                                 'ft'),
                                         'altitude_final': (   np.float64(820.0),
                                                               'ft'),
                                         'altitude_bounds': (   (   np.float64(320.0),
                                                                    np.float64(27040.0)),
                                                                'ft'),
                                         'throttle_enforcement': 'path_constraint',
                                         'time_initial_bounds': (   (   np.float64(177.0),
                                                                        np.float64(531.0)),
                                                                    'min'),
                                         'time_duration_bounds': (   (   np.float64(15.0),
                                                                         np.float64(45.0)),
                                                                     'min'),
                                         'distance_solve_segments': False},
                     'initial_guesses': {   'time': (   [   np.float64(354.0),
                                                            np.float64(30.0)],
                                                        'min')}},
    'post_mission': {   'include_landing': False,
                        'constrain_range': True,
                        'target_range': (np.float64(2074.67), 'nmi')}}
